POST http://localhost:3001/api/patients/d2773822-f723-11e9-8f0b-362b9e155667/entries
Content-Type: application/json

{
  "description": "Testing POST endpoint for entry: HealthCheck without diagnosis codes.",
  "date": "2023-07-03",
  "specialist": "Full Stack Developer Student",
  "type": "HealthCheck",
  "healthCheckRating": 3
}

###
POST http://localhost:3001/api/patients/d2773822-f723-11e9-8f0b-362b9e155667/entries
Content-Type: application/json

{
  "description": "Testing POST endpoint for entry: HealthCheck with diagnosis codes.",
  "date": "2023-07-03",
  "specialist": "Full Stack Developer Student",
  "type": "HealthCheck",
  "healthCheckRating": 3,
  "diagnosisCodes": ["Z74.3"]

}

###
POST http://localhost:3001/api/patients/d2773822-f723-11e9-8f0b-362b9e155667/entries
Content-Type: application/json

{
  "description": "Testing POST endpoint for entry: HealthCheck with faulty health check rating.",
  "date": "2023-07-03",
  "specialist": "Full Stack Developer Student",
  "type": "HealthCheck",
  "healthCheckRating": 5,
  "diagnosisCodes": ["Z74.3"]

}


###
POST http://localhost:3001/api/patients/d2773822-f723-11e9-8f0b-362b9e155667/entries
Content-Type: application/json

{
  "description": "Testing entry POST endpoint : Occupational Healthcare entry. With healthCheck rating incldued and missing employerName",
  "date": "2023-07-03",
  "specialist": "Full Stack Developer Student",
  "type": "OccupationalHealthcare",
  "healthCheckRating": 5,
  "diagnosisCodes": ["Z74.3"]

}

###
POST http://localhost:3001/api/patients/d2773822-f723-11e9-8f0b-362b9e155667/entries
Content-Type: application/json

{
  "description": "Testing entry POST endpoint : Occupational Healthcare entry with invalid healthCheckRating included.",
  "date": "2023-07-03",
  "specialist": "Full Stack Developer Student",
  "type": "OccupationalHealthcare",
  "diagnosisCodes": ["Z74.3"],
  "employerName": "Unknown",
  "healthCheckRating": 5
}

###
POST http://localhost:3001/api/patients/d2773822-f723-11e9-8f0b-362b9e155667/entries
Content-Type: application/json

{
  "description": "Testing entry POST endpoint : Occupational Healthcare entry. With valid sickLeave duration",
  "date": "2023-07-03",
  "specialist": "Full Stack Developer Student",
  "type": "OccupationalHealthcare",
  "diagnosisCodes": ["Z74.3"],
  "employerName": "Unknown",
  "sickLeave": {
    "startDate": "2023-07-03",
    "endDate": "2023-07-13"
  }
}

###
POST http://localhost:3001/api/patients/d2773822-f723-11e9-8f0b-362b9e155667/entries
Content-Type: application/json

{
  "description": "Testing entry POST endpoint : Occupational Healthcare entry. With invalid sickLeave duration",
  "date": "2023-07-03",
  "specialist": "Full Stack Developer Student",
  "type": "OccupationalHealthcare",
  "diagnosisCodes": ["Z74.3"],
  "employerName": "Unknown",
  "sickLeave": {
    "startDate": "2023-07-03",
    "endDate": "2023-17-13"
  }
}

###
POST http://localhost:3001/api/patients/d2773822-f723-11e9-8f0b-362b9e155667/entries
Content-Type: application/json

{
  "description": "Testing entry POST endpoint : Occupational Healthcare entry. With invalid sickLeave duration",
  "date": "2023-07-03",
  "specialist": "Full Stack Developer Student",
  "type": "OccupationalHealthcare",
  "diagnosisCodes": ["Z74.3"],
  "employerName": "Unknown",
  "sickLeave": {
    "startDate": "2023-07-03"
  }
}

###
POST http://localhost:3001/api/patients/d2773822-f723-11e9-8f0b-362b9e155667/entries
Content-Type: application/json

{
  "description": "Testing entry POST endpoint : Hospital entry without discharge",
  "date": "2023-07-03",
  "specialist": "Full Stack Developer Student",
  "type": "Hospital",
  "diagnosisCodes": ["Z74.3"]
}

###
POST http://localhost:3001/api/patients/d2773822-f723-11e9-8f0b-362b9e155667/entries
Content-Type: application/json

{
  "description": "Testing entry POST endpoint : Hospital entry with valid discharge",
  "date": "2023-07-03",
  "specialist": "Full Stack Developer Student",
  "type": "Hospital",
  "diagnosisCodes": ["Z74.3"],
  "discharge": {
    "date": "2023-07-03",
    "criteria": "Supervision no longer needed"
  }
}

###
POST http://localhost:3001/api/patients/d2773822-f723-11e9-8f0b-362b9e155667/entries
Content-Type: application/json

{
  "description": "Testing entry POST endpoint : Hospital entry with invalid discharge",
  "date": "2023-07-03",
  "specialist": "Full Stack Developer Student",
  "type": "Hospital",
  "diagnosisCodes": ["Z74.3"],
  "discharge": {
    "date": "2023-07-83",
    "criteria": "Supervision no longer needed"
  }
}

###
POST http://localhost:3001/api/patients/d2773822-f723-11e9-8f0b-362b9e155667/entries
Content-Type: application/json

{
  "description": "Testing entry POST endpoint : Hospital entry with invalid discharge",
  "date": "2023-07-03",
  "specialist": "Full Stack Developer Student",
  "type": "Hospital",
  "diagnosisCodes": ["Z74.3"],
  "discharge": {
    "date": "2023-07-03"
  }
}

###
POST http://localhost:3001/api/patients/d2773822-f723-11e9-8f0b-362b9e155667/entries
Content-Type: application/json

{
  "description": "Testing entry POST endpoint : Hospital entry with valid discharge",
  "date": "2023-07-03",
  "specialist": "Full Stack Developer Student",
  "type": "Hospital",
  "discharge": {
    "date": "2023-07-03",
    "criteria": "Supervision no longer needed"
  }
}

###
POST http://localhost:3001/api/patients/d2773822-f723-11e9-8f0b-362b9e155667/entries
Content-Type: application/json

{
  "description": "Testing entry POST endpoint : entry without type",
  "date": "2023-07-03",
  "specialist": "Full Stack Developer Student",
  "discharge": {
    "date": "2023-07-03",
    "criteria": "Supervision no longer needed"
  }
}

###
POST http://localhost:3001/api/patients/d2773822-f723-11e9-8f0b-362b9e155667/entries
Content-Type: application/json

{
  "description": "Testing entry POST endpoint : entry with invalid type",
  "date": "2023-07-03",
  "specialist": "Full Stack Developer Student",
  "type": "DevelopmentType",
  "discharge": {
    "date": "2023-07-03",
    "criteria": "Supervision no longer needed"
  }
}

###
POST http://localhost:3001/api/patients/d277383-11e9-8f0b-362b9e155667/entries
Content-Type: application/json

{
  "description": "Testing entry POST endpoint : faulty patient id in the request url",
  "date": "2023-07-03",
  "specialist": "Full Stack Developer Student",
  "type": "Hospital",
  "discharge": {
    "date": "2023-07-03",
    "criteria": "Supervision no longer needed"
  }
}
