GET http://localhost:3001/api/patients

###
POST http://localhost:3001/api/patients
Content-Type: application/json

{
  "id": "d2773akua-f723-11e9-8f0b-362b9e155667",
  "name": "Aku Ankka",
  "dateOfBirth": "1934-03-13",
  "ssn": "13031934-AKUA",
  "gender": "male",
  "occupation": "Sekatyömies"
}

###
POST http://localhost:3001/api/patients
Content-Type: application/json

{
  "name": "Ash Ketchum",
  "dateOfBirth": "1992-02-31",
  "ssn": "31021992-pika",
  "gender": "male",
  "occupation": "Pokémon Trainer"
}

###
POST http://localhost:3001/api/patients/d2773822-f723-11e9-8f0b-362b9e155667/entries
Content-Type: application/json

{
  "dummy": "variable"
}