GET http://localhost:3001/api/patients

###
POST http://localhost:3001/api/patients
Content-Type: application/json

{
  "id": "lmao-lol-13",
  "name": "Aku Ankka",
  "dateOfBirth": "1934-03-13",
  "ssn": "13031934-AKUA",
  "gender": "male",
  "occupation": "Sekatyömies"
}